const allInstalls = [
  {
    id: 1,
    pm: "Guy Farley",
    storeNum: 234,
    location: "Bozeman, MT",
    campaign: "Omni-Heat 4D",
    vendorName: "Vectra",
    vendorPhone: "(555) 412-4343",
    installDate: "10-22-22",
    installTime: "6AM",
    installer: "The Install Guys",
    installerPhone: "(555) 212-5454",
    installerNotes: "",
    complete: false,
    completionPics: {},
    revisitNeeded: true,
    revisitDate: 10 - 22 - 24,
    pmNotes: ""
  },
  {
    id: 2,
    pm: "Guy Farley",
    storeNum: 123,
    location: "Fargo, SD",
    campaign: "Omni-Heat 4D",
    vendorName: "Vectra",
    vendorPhone: "(555) 412-4343",
    installDate: "10-24-22",
    installTime: "7AM",
    installer: "Installation Nation",
    installerPhone: "(555) 989-8787",
    installerNotes: "",
    complete: false,
    completionPics: {},
    revisitNeeded: false,
    revisitDate: null,
    pmNotes: ""
  },
  {
    id: 3,
    pm: "Guy Farley",
    storeNum: 565,
    location: "Nashville, TN",
    campaign: "Omni-Heat 4D",
    vendorName: "Vectra",
    vendorPhone: "(555) 412-4343",
    installDate: "10-23-22",
    installTime: "6AM",
    installer: "Installs R Us",
    installerPhone: "(555) 858-7789",
    installerNotes: "",
    complete: true,
    completionPics: {},
    revisitNeeded: false,
    revisitDate: null,
    pmNotes: ""
  }
]

export default allInstalls;