
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import * as React from 'react';

export default function Layout({ children, home }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Install Tracker App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Retail Graphic Installation App!
        </h1>

        <p className={styles.description}>
          A work in progress...
        </p>

        <div className={styles.grid}>
        </div>
        {children}
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
}